#!/bin/bash

set -e -o pipefail

XMLLINT_VERSAO_MINIMA='20706'
CARTAS_DIR='cartas-servico'

if ! which xmllint > /dev/null; then
  echo 'Commando xmllint não encontrado. verifique se você tem o pacote libxml instalado corretamente.'
  exit -1
fi

XMLLINT_VERSAO_ATUAL=$(xmllint --version 2>&1 | head -n1 | grep -Eo '[0-9]+' || echo 0)

if [ "$XMLLINT_VERSAO_ATUAL" -lt "$XMLLINT_VERSAO_MINIMA" ]; then
  echo "Versão do xmllint é atualmente ${XMLLINT_VERSAO_ATUAL}. Versão mínima é ${XMLLINT_VERSAO_MINIMA}."
  exit -1
fi

if [ ! -d "$CARTAS_DIR" ]; then
  echo "Diretório de cartas de serviço não encontrado em: $(pwd)"
  echo 'Script deve ser executado no diretório principal do projeto'
  exit -1
fi

#for xml in $CARTAS_DIR/v2/servicos/*.xml; do
#  xmllint --schema $CARTAS_DIR/v2/servico.xsd --noout "$xml"
#done

for xml in $CARTAS_DIR/v3/servicos/*.xml; do
  xmllint --schema $CARTAS_DIR/v3/servico.xsd --noout "$xml"
done
