#!/bin/bash

set -e
set -o pipefail

if [ ! -d "$SNAP_CACHE_DIR" ]; then
  echo "Diretório de cache do Snap ($SNAP_CACHE_DIR) não configurado"
  exit -1
fi

rm -rf "${SNAP_CACHE_DIR}/gh-pages"
git clone -b 'gh-pages' git@github.com:servicosgovbr/cartas-de-servico.git "${SNAP_CACHE_DIR}/gh-pages"

pushd "${SNAP_CACHE_DIR}/gh-pages"
  rm -rf *
popd

pushd docs
  ln -s "${SNAP_CACHE_DIR}/node_modules" "node_modules"
  npm install gitbook-cli
  ./node_modules/.bin/gitbook build

  mv _book/* "${SNAP_CACHE_DIR}/gh-pages/"
popd

pushd "${SNAP_CACHE_DIR}/gh-pages"
  git add -A
  git commit -am "Atualiza documentação para a versão ${SNAP_COMMIT_SHORT:-desconhecida} (build #${SNAP_PIPELINE_COUNTER:-desconhecida})"
  git push origin gh-pages
popd
